server:
  port: 8080


sendgrid:
  apiKey: ${SENDGRID_API_KEY:}
  from: "seest97@gmail.com"
  fromName: "Ticketing"
  to: "seest97@gmail.com"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketingdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: WARN
    it.unito.cloudnative.ticketing: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
