server:
  port: ${PORT:8080}

sendgrid:
  apiKey: ${SENDGRID_API_KEY:}
  from: ${SENDGRID_FROM:seest97@gmail.com}
  fromName: ${SENDGRID_FROM_NAME:Ticketing}
  to: ${SENDGRID_TO:seest97@gmail.com}

spring:
  datasource:

    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketingdb?sslmode=disable}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: WARN
    it.unito.cloudnative.ticketing: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
