--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment (
    id bigint NOT NULL,
    author character varying(255) NOT NULL,
    content character varying(4000) NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    parent_id bigint,
    ticket_id bigint NOT NULL
);


ALTER TABLE public.comment OWNER TO postgres;

--
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(2000),
    priority character varying(255),
    status character varying(255),
    title character varying(255),
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.ticket OWNER TO postgres;

--
-- Name: ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: comment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comment (id, author, content, created_at, updated_at, parent_id, ticket_id) FROM stdin;
3	seest97@gmail.com	aaa	2025-09-10 11:48:23.089012+00	2025-09-10 11:48:23.089012+00	\N	3
4	seest97@gmail.com	aaaa	2025-09-10 12:00:47.723069+00	2025-09-10 12:00:47.723069+00	\N	3
\.


--
-- Data for Name: ticket; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket (id, created_at, description, priority, status, title, updated_at) FROM stdin;
2	2025-08-09 01:25:42.538728	Non riesco ad accedere	HIGH	OPEN	Bug nel login	2025-08-09 01:25:42.539366
3	2025-08-09 03:32:07.994693	aaaa	LOW	OPEN	aaa	2025-08-09 03:32:07.994693
4	2025-08-09 21:47:42.349914	test mail	LOW	OPEN	test mail	2025-08-09 21:47:42.349914
5	2025-09-10 13:47:46.081734	aaaa	LOW	OPEN	aaa	2025-09-10 13:47:46.081734
6	2025-09-10 14:00:31.595361	aaaa	LOW	OPEN	aaa	2025-09-10 14:00:31.595361
7	2025-09-10 14:08:19.313727	test	LOW	OPEN	test	2025-09-10 14:08:19.313727
8	2025-09-10 14:12:13.575268	www	LOW	OPEN	www	2025-09-10 14:12:13.575268
9	2025-09-10 14:13:53.216542	aaaa	LOW	OPEN	aaa	2025-09-10 14:13:53.21705
10	2025-09-10 14:21:16.329641	aaa	LOW	OPEN	aa	2025-09-10 14:21:16.329641
\.


--
-- Name: comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comment_id_seq', 5, true);


--
-- Name: ticket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_id_seq', 10, true);


--
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);


--
-- Name: comment fkde3rfu96lep00br5ov0mdieyt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkde3rfu96lep00br5ov0mdieyt FOREIGN KEY (parent_id) REFERENCES public.comment(id);


--
-- Name: comment fksyf8wt2qb7rhcau6v3p4axrba; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fksyf8wt2qb7rhcau6v3p4axrba FOREIGN KEY (ticket_id) REFERENCES public.ticket(id);


--
-- PostgreSQL database dump complete
--

